"""Authenticated, streaming, lossless archive download.

Signed paths generated by HA's auth/sign_path retain the signing user's access.
The browser downloads directly; raw histories need not fit in a WebSocket or
browser Blob. Database I/O is confined to the executor.
"""
from __future__ import annotations

import asyncio
from datetime import datetime, timezone
import logging

from aiohttp import web
from homeassistant.components.http import HomeAssistantView
from homeassistant.components.http.const import KEY_HASS_USER
from homeassistant.helpers.http import KEY_HASS

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)


def _next_chunk(stream, maximum: int = 65536) -> bytes:
    parts, size = [], 0
    for part in stream:
        value = part.encode('utf-8')
        parts.append(value)
        size += len(value)
        if size >= maximum:
            break
    return b''.join(parts)


class BatteryChargeManagerExportView(HomeAssistantView):
    """Read-only export for the authenticated administrator, never public."""

    url = '/api/battery_charge_manager/export/{entry_id}'
    name = 'api:battery_charge_manager:export'
    requires_auth = True

    async def get(self, request: web.Request, entry_id: str) -> web.StreamResponse:
        user = request.get(KEY_HASS_USER)
        if user is None or not user.is_admin:
            raise web.HTTPForbidden()
        manager = request.app[KEY_HASS].data.get(DOMAIN, {}).get(entry_id)
        if manager is None:
            raise web.HTTPNotFound()
        stream = None
        response = web.StreamResponse(headers={
            'Content-Type':'application/json; charset=utf-8', 'Cache-Control':'no-store',
            'Content-Disposition':'attachment; filename="battery-charge-manager-'
                +datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')+'.json"'})
        # Do not abandon an executing generator on cancellation: closing it while
        # the executor is still advancing it would leave a DB snapshot open.
        pending = None
        try:
            stream = await manager.async_archive_export()
            while True:
                pending = asyncio.ensure_future(manager._io(_next_chunk,stream))
                chunk = await asyncio.shield(pending)
                pending = None
                if not response.prepared:
                    await response.prepare(request)
                if not chunk:
                    break
                await response.write(chunk)
            await response.write_eof()
            return response
        except asyncio.CancelledError:
            if pending is not None:
                try:
                    await pending
                except Exception:
                    pass
            raise
        except Exception as err:
            _LOGGER.error('Archive download failed without changing stored measurements: %s',err)
            if response.prepared:
                # Do not terminate the body cleanly: an incomplete archive must
                # be a failed download, not a successful truncated JSON file.
                if request.transport is not None:
                    request.transport.close()
                raise
            raise web.HTTPInternalServerError(text='Archive export failed. Stored data were not deleted.') from err
        finally:
            if stream is not None:
                if hasattr(stream,'close'):
                    await manager._io(stream.close)
